// TO CALCULATE A NUMBER'S NEGATIVE NUMBER USING BINARY CONVERSION
// FIRST OF ALL ADD A ZERO IN THE FIRST PLACE i.e 1010 --> 01010
// THE CONCEPT OF 1'S COMPLEMENT IS TO FLIP ALL THE PLACES OF BINARY NUMBER i.e 1-->0 & 0-->1 . (THIS IS THE SECOND STEP)
// AT LAST ADD 1 TO THE CONVERTED NUMBER USING BINARY ADDITION  (two's complement)

#include<iostream>
using namespace std;

int main(){
    
}